"""baseline schema

Revision ID: a4f19a6ba949
Revises: 
Create Date: 2026-06-17 02:00:16.573217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'a4f19a6ba949'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # pgvector extension must exist before the speech_embeddings VECTOR column.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('meetings',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('assembly', sa.Integer(), nullable=False),
    sa.Column('meeting_date', sa.DateTime(), nullable=False),
    sa.Column('meeting_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('meeting_id')
    )
    op.create_table('members',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('name_english', sa.String(length=255), nullable=False),
    sa.Column('name_welsh', sa.String(length=255), nullable=True),
    sa.Column('biography_english', sa.Text(), nullable=True),
    sa.Column('biography_welsh', sa.Text(), nullable=True),
    sa.Column('sort_code', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_table('sync_checkpoints',
    sa.Column('checkpoint_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_sync_date', sa.DateTime(), nullable=False),
    sa.Column('last_meeting_id', sa.DateTime(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('checkpoint_id')
    )
    op.create_table('member_job_titles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('job_title_english', sa.String(length=255), nullable=True),
    sa.Column('job_title_welsh', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.meeting_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'meeting_id', name='uq_member_meeting_title')
    )
    op.create_index(op.f('ix_member_job_titles_meeting_id'), 'member_job_titles', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_member_job_titles_member_id'), 'member_job_titles', ['member_id'], unique=False)
    op.create_table('raw_contributions',
    sa.Column('contribution_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('assembly', sa.Integer(), nullable=True),
    sa.Column('meeting_date', sa.DateTime(), nullable=True),
    sa.Column('contribution_order_id', sa.Integer(), nullable=True),
    sa.Column('contribution_language', sa.String(length=10), nullable=True),
    sa.Column('contribution_time', sa.DateTime(), nullable=True),
    sa.Column('contribution_spoken_seneddtv', sa.String(length=500), nullable=True),
    sa.Column('contribution_translated_seneddtv', sa.String(length=500), nullable=True),
    sa.Column('agenda_item_id', sa.String(length=100), nullable=True),
    sa.Column('agenda_item_welsh', sa.String(length=500), nullable=True),
    sa.Column('agenda_item_english', sa.String(length=500), nullable=True),
    sa.Column('contribution_type', sa.String(length=10), nullable=True),
    sa.Column('attendee_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('member_name_english', sa.String(length=255), nullable=True),
    sa.Column('member_biog_english', sa.Text(), nullable=True),
    sa.Column('member_biog_welsh', sa.Text(), nullable=True),
    sa.Column('member_job_title_english', sa.String(length=255), nullable=True),
    sa.Column('member_job_title_welsh', sa.String(length=255), nullable=True),
    sa.Column('member_sortcode', sa.String(length=50), nullable=True),
    sa.Column('contribution_english', sa.Text(), nullable=True),
    sa.Column('contribution_welsh', sa.Text(), nullable=True),
    sa.Column('contribution_verbatim', sa.Text(), nullable=True),
    sa.Column('contribution_translated', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.meeting_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('contribution_id')
    )
    op.create_table('speeches',
    sa.Column('speech_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('assembly', sa.Integer(), nullable=True),
    sa.Column('agenda_item_id', sa.String(length=100), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('speaker_name', sa.String(length=255), nullable=False),
    sa.Column('speech_language', sa.String(length=50), nullable=True),
    sa.Column('speech_text', sa.Text(), nullable=False),
    sa.Column('source_row_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.meeting_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['members.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('speech_id')
    )
    op.create_table('classified_contributions',
    sa.Column('contribution_id', sa.Integer(), nullable=False),
    sa.Column('row_type', sa.Enum('SPEECH', 'PROCEDURAL', 'NOISE', 'ORAL_QUESTION', 'TOPICAL_QUESTION', name='rowtypeenum'), nullable=False),
    sa.Column('classification_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['contribution_id'], ['raw_contributions.contribution_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contribution_id')
    )
    op.create_table('clean_contributions',
    sa.Column('contribution_id', sa.Integer(), nullable=False),
    sa.Column('contribution_verbatim_clean', sa.Text(), nullable=True),
    sa.Column('contribution_translated_clean', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contribution_id'], ['raw_contributions.contribution_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contribution_id')
    )
    op.create_table('oral_questions',
    sa.Column('question_id', sa.String(length=50), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('contribution_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['raw_contributions.contribution_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.meeting_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id'),
    sa.UniqueConstraint('contribution_id')
    )
    op.create_index(op.f('ix_oral_questions_meeting_id'), 'oral_questions', ['meeting_id'], unique=False)
    op.create_table('procedural_events',
    sa.Column('procedural_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('agenda_item_id', sa.String(length=100), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('speaker_name', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('source_contribution_id', sa.Integer(), nullable=True),
    sa.Column('senedd_tv_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.meeting_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_contribution_id'], ['raw_contributions.contribution_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('procedural_id')
    )
    op.create_table('speech_embeddings',
    sa.Column('embedding_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('speech_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=True),
    sa.Column('embedding_vector', Vector(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['speech_id'], ['speeches.speech_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('embedding_id')
    )
    op.create_table('speech_parts',
    sa.Column('speech_part_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('speech_id', sa.Integer(), nullable=False),
    sa.Column('contribution_id', sa.Integer(), nullable=False),
    sa.Column('contribution_order_id', sa.Integer(), nullable=True),
    sa.Column('contribution_time', sa.DateTime(), nullable=True),
    sa.Column('spoken_url', sa.String(length=500), nullable=True),
    sa.Column('translated_url', sa.String(length=500), nullable=True),
    sa.Column('verbatim_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contribution_id'], ['raw_contributions.contribution_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speech_id'], ['speeches.speech_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('speech_part_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speech_parts')
    op.drop_table('speech_embeddings')
    op.drop_table('procedural_events')
    op.drop_index(op.f('ix_oral_questions_meeting_id'), table_name='oral_questions')
    op.drop_table('oral_questions')
    op.drop_table('clean_contributions')
    op.drop_table('classified_contributions')
    op.drop_table('speeches')
    op.drop_table('raw_contributions')
    op.drop_index(op.f('ix_member_job_titles_member_id'), table_name='member_job_titles')
    op.drop_index(op.f('ix_member_job_titles_meeting_id'), table_name='member_job_titles')
    op.drop_table('member_job_titles')
    op.drop_table('sync_checkpoints')
    op.drop_table('members')
    op.drop_table('meetings')
    # Drop the enum type explicitly — Postgres does not remove it with the table.
    op.execute("DROP TYPE IF EXISTS rowtypeenum")
    # ### end Alembic commands ###
