"""add artifact_watch table for late-publication sync

Revision ID: fccbf37e6bae
Revises: 7c1e757d7577
Create Date: 2026-06-19 00:44:07.844148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fccbf37e6bae'
down_revision: Union[str, Sequence[str], None] = '7c1e757d7577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_watch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.meeting_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'artifact_type', name='uq_watch_meeting_artifact')
    )
    op.create_index(op.f('ix_artifact_watch_meeting_id'), 'artifact_watch', ['meeting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifact_watch_meeting_id'), table_name='artifact_watch')
    op.drop_table('artifact_watch')
    # ### end Alembic commands ###
