"""add votes and vote_records tables

Revision ID: 764c34b20b0e
Revises: 7a0d6f8bf14c
Create Date: 2026-06-19 00:13:08.277893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764c34b20b0e'
down_revision: Union[str, Sequence[str], None] = '7a0d6f8bf14c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('vote_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contribution_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('assembly', sa.Integer(), nullable=True),
    sa.Column('agenda_item_id', sa.String(length=100), nullable=True),
    sa.Column('agenda_item_english', sa.String(length=500), nullable=True),
    sa.Column('agenda_item_welsh', sa.String(length=500), nullable=True),
    sa.Column('vote_name_english', sa.Text(), nullable=True),
    sa.Column('vote_name_welsh', sa.Text(), nullable=True),
    sa.Column('total_for', sa.Integer(), nullable=True),
    sa.Column('total_against', sa.Integer(), nullable=True),
    sa.Column('total_abstain', sa.Integer(), nullable=True),
    sa.Column('result_english', sa.String(length=255), nullable=True),
    sa.Column('result_welsh', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contribution_id'], ['raw_contributions.contribution_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.meeting_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vote_id'),
    sa.UniqueConstraint('contribution_id')
    )
    op.create_index(op.f('ix_votes_meeting_id'), 'votes', ['meeting_id'], unique=False)
    op.create_table('vote_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.Enum('FOR', 'AGAINST', 'ABSTAIN', 'DID_NOT_VOTE', name='voteresultenum'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vote_id'], ['votes.vote_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vote_id', 'member_id', name='uq_vote_member')
    )
    op.create_index(op.f('ix_vote_records_member_id'), 'vote_records', ['member_id'], unique=False)
    op.create_index(op.f('ix_vote_records_vote_id'), 'vote_records', ['vote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vote_records_vote_id'), table_name='vote_records')
    op.drop_index(op.f('ix_vote_records_member_id'), table_name='vote_records')
    op.drop_table('vote_records')
    op.drop_index(op.f('ix_votes_meeting_id'), table_name='votes')
    op.drop_table('votes')
    # Enum type is not dropped by drop_table; remove it so re-upgrade is clean.
    op.execute("DROP TYPE IF EXISTS voteresultenum")
    # ### end Alembic commands ###
