"""add written_contributions table for QNR

Revision ID: 7c1e757d7577
Revises: 764c34b20b0e
Create Date: 2026-06-19 00:19:11.938482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c1e757d7577'
down_revision: Union[str, Sequence[str], None] = '764c34b20b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('written_contributions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('assembly', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('agenda_item_id', sa.String(length=100), nullable=True),
    sa.Column('agenda_item_english', sa.String(length=500), nullable=True),
    sa.Column('agenda_item_welsh', sa.String(length=500), nullable=True),
    sa.Column('qa_role', sa.Enum('QUESTION', 'ANSWER', name='qaroleenum'), nullable=False),
    sa.Column('pair_id', sa.String(length=50), nullable=True),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.Column('speaker_name_english', sa.String(length=255), nullable=True),
    sa.Column('speaker_job_title_english', sa.String(length=255), nullable=True),
    sa.Column('speaker_job_title_welsh', sa.String(length=255), nullable=True),
    sa.Column('text_english', sa.Text(), nullable=True),
    sa.Column('text_welsh', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.meeting_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['members.member_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'order_index', name='uq_written_meeting_order')
    )
    op.create_index(op.f('ix_written_contributions_meeting_id'), 'written_contributions', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_written_contributions_pair_id'), 'written_contributions', ['pair_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_written_contributions_pair_id'), table_name='written_contributions')
    op.drop_index(op.f('ix_written_contributions_meeting_id'), table_name='written_contributions')
    op.drop_table('written_contributions')
    # Enum type is not dropped by drop_table; remove it so re-upgrade is clean.
    op.execute("DROP TYPE IF EXISTS qaroleenum")
    # ### end Alembic commands ###
